name: JamieOpso
favicon: null
layout_spectrum: 0.99711
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c3b392'
    - '#5a5b56'
    - '#b78d01'
  brandStrength: 0.40657027205452323
  lightness: 0.259806934511289
  saturation: 0.5
  rhythmicContrast: 0.4861275313887745
purpose: []
