name: JamieOpso
favicon: null
layout_spectrum: 0.99711
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#112f53'
    - '#2a5a71'
    - '#7fa9ab'
    - '#85d4e1'
    - '#bffefc'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
